export const tasksActionTypes = {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  EDIT_TASK_CATEGORY: 'EDIT_TASK_CATEGORY',
  GET_TASKS: 'GET_TASKS',
  TOGGLE_IS_DONE: 'TOGGLE_IS_DONE',
  TOGGLE_TASKS_FETCHING: 'TOGGLE_TASKS_FETCHING',
  CLEAR_TASKS: 'CLEAR_TASKS',
};
