export const categoriesActionTypes = {
  ADD_CATEGORY: 'ADD_CATEGORY',
  ADD_NESTED_CATEGORY: 'ADD_NESTED_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  GET_CATEGORIES: 'GET_CATEGORIES',
  TOGGLE_CATEGORIES_FETCHING: 'TOGGLE_CATEGORIES_FETCHING',
};
